In [11]:
import pandas as pd
import numpy as np
from scipy import stats

# 2

Классификатор C4.5 и три его модификации: с оптимизацией гиперпараметра m, гиперпараметра cf и с одновременной оптимизацией обоих гиперпараметров. Эти четыре классификатора сравнивались на 14 наборах данных. На каждом датасете был посчитан AUC каждого классификатора. Данные записаны в файле:
AUCs.txt

Используя критерий знаковых рангов, проведите попарное сравнение каждого классификатора с каждым. Выберите два классификатора, различие между которыми наиболее статистически значимо. 

In [22]:
data=pd.read_table('AUCs.txt')
data.head()

Unnamed: 0   C4.5  C4.5+m  C4.5+cf  C4.5+m+cf
0           adult (sample)  0.763   0.768    0.771      0.798
1            breast cancer  0.599   0.591    0.590      0.569
2  breast cancer wisconsin  0.954   0.971    0.968      0.967
3                      cmc  0.628   0.661    0.654      0.657
4               ionosphere  0.882   0.888    0.886      0.898

# Критерий знаковых рангов Уилкоксона
$H_0\colon med\left(X_1-X_2\right)=0,$

$H_1\colon med\left(X_1-X_2\right)\neq0$

In [40]:
minimum =1
a=0
b=0
p=[]
for i in range(1,5):
    for j in range(1,5):
        if i>j:
            p.append(stats.wilcoxon(data.iloc[:,i] - data.iloc[:,j]).pvalue)
            if stats.wilcoxon(data.iloc[:,i] - data.iloc[:,j]).pvalue<minimum:
                minimum = stats.wilcoxon(data.iloc[:,i] - data.iloc[:,j]).pvalue
                a=i
                b=j
            

In [41]:
print(minimum)
print(a,b)
print(p)

0.01075713311978963
2 1
[0.01075713311978963, 0.861262330095348, 0.046332729793395394, 0.015906444101703374, 0.3278256758446406, 0.022909099354356588]


Сколько статистически значимых на уровне 0.05 различий мы обнаружили?

4, тк 4 значения pvalue<0.05, при них нулевая гипотеза о равенстве средних отвергается

# 5

Сравнивая 4 классификатора между собой, мы проверили 6 гипотез. Давайте сделаем поправку на множественную проверку. Начнём с метода Холма. Сколько гипотез можно отвергнуть на уровне значимости 0.05 после поправки этим методом?

In [29]:
from statsmodels.sandbox.stats.multicomp import multipletests 

In [30]:
reject, p_corrected, a1, a2 = multipletests(p, 
                                            alpha = 0.05, 
                                            method = 'holm') 

In [35]:
reject


array([False, False, False, False, False, False])

In [37]:
p_corrected

array([0.0645428 , 0.86126233, 0.13899819, 0.07953222, 0.65565135,
       0.0916364 ])

# 6


In [42]:
reject, p_corrected, a1, a2 = multipletests(p, 
                                            alpha = 0.05, 
                                            method = 'fdr_bh') 

In [43]:
reject

array([ True, False, False,  True, False,  True])

In [44]:
p_corrected

array([0.0458182 , 0.86126233, 0.06949909, 0.0458182 , 0.39339081,
       0.0458182 ])